services:
  beacon:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    deploy:
      placement:
          constraints:
            - node.role == manager
    networks:
      # - host
      - test
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "9000:9000"
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
  node:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    depends_on:
      - beacon
    deploy:
      replicas: 20
      placement:
          max_replicas_per_node: 1
          constraints:
            - node.role == worker
            # - node.labels.mynode == deterlab
    networks:
      - test
      # - host
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "8888:8888"
      # - target: 8888
      #   published: 8888
      #   mode: host
    environment:
      # - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_IP=beacon
      - BEACON_PORT=9000
      - PORT=8888
      - ROUND_TIME=5
      - TOLERANCE=2
      - TAU=10
      - TOTAL_STAKE=25
      - MOCK_TRANSACTIONS=false           # set to true to use randomly generated transactions
      - MAXIMUM_NUM_PEERS=8          # maximum number of peers a node can have
      - MINIMUM_NUM_PEERS=4          # minimum number of peers a node can have
      - NUM_PEERS_SEND = 5           # number of peers sent by beacon to nodes who just entered or need more
      
      # Be careful not to commit the following information to github
      - SSH_ADDRESS=
      - SSH_PASSWORD=
      - SCP_PATH=

    command: /bin/bash demo/run_node.sh

networks:
  test:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "10.60.0.0/16"
# test:
#   name: test
#   driver: overlay
#   attachable: true
  # host:
  #   name: host
  #   external: true
