services:
  beacon:
    # image: georgejuniorg/cpos_v2
    build: .
    tty: true
    volumes:
      - .:/cpos
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
  node:
    # image: georgejuniorg/cpos_v2
    build: .
    tty: true
    depends_on:
      - beacon
    deploy:
      replicas: 10
    volumes:
      - .:/cpos
    environment:
      - BEACON_IP=beacon
      - BEACON_PORT=9000
      - PORT=8888
      - MOCK_TRANSACTIONS=false           # set to true to use randomly generated transactions

      # Be careful not to commit the following information to github
      - SSH_ADDRESS=
      - SSH_PASSWORD=
      - SCP_PATH=

    command: /bin/bash demo/run_node.sh
